image: docker

services:
 - docker:dind

before_script:
 - export
 - docker login registry.gitlab.com --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD

build:
  script:
   - docker pull registry.gitlab.com/xcore89/skillbox:latest
   - docker build . --tag registry.gitlab.com/xcore89/skillbox:$CI_BUILD_REF --tag registry.gitlab.com/xcore89/skillbox:latest
   - docker push registry.gitlab.com/xcore89/skillbox:latest
   - docker push registry.gitlab.com/xcore89/skillbox:$CI_BUILD_REF
